import fs from "node:fs";
import path from "node:path";
import { command, fail, info, link, ok, out, step, warn } from "../format.ts";
import { detectRepoRoot } from "../paths.ts";
import { promptMultiline, promptSelect, promptYesNo, prompts } from "../prompts.ts";
import { harnessAgentsDir, harnessRootDir, harnessSkillsDir, hasGeneratedTeam, hasPrd } from "./harness-paths.ts";
import { state } from "./state.ts";
import { autobuildCommand, buildTeamPrompt, headlessCmdFor, PRD_HEADLESS_MSG, prdSourceForTeam, runSkillHeadless } from "./skills.ts";
import { diagnoseAutoDraftFail, draftCommit } from "./plan.ts";
import { engineDecision, engineRunArgs, openCliFor, runEngineDetached, stopEngine } from "./engine.ts";
import { prdDocName, readEngineState, type ResumeOptions, setupStateForRepo } from "./repo-state.ts";
import { printEngineStatus, printMonitorCommands } from "./commands.ts";

export function printResumeWhere(): void {
  const ideaPath = path.join(state.repoDir, "docs", "IDEA.md");
  const idea = fs.existsSync(ideaPath);
  const prd = hasPrd();
  const team = hasGeneratedTeam();
  const manifest = fs.existsSync(path.join(state.repoDir, "docs", "EXECUTION-MANIFEST.json"));
  const engine = readEngineState();

  step("Resume project state");
  out("");
  out(`  Repository  : ${link(state.repoDir)}`);
  out(`  Harness     : ${state.harnessLabel} (${harnessRootDir()}/)`);
  out("");
  info("Where you are:");
  out(`    - Project idea       : ${idea ? `yes  ${link(ideaPath)}` : "no"}`);
  out(`    - PRD                : ${prd ? `yes  ${link(path.join(state.repoDir, "docs", prdDocName()))}` : "no"}`);
  out(`    - Agent team         : ${team ? `yes  ${link(harnessAgentsDir() + "/")}` : "no"}`);
  out(`    - Execution manifest : ${manifest ? "yes" : "no"}`);
  if (engine) out(`    - Engine run         : ${engine.status ?? "unknown"}${engine.runId ? ` (run ${engine.runId})` : ""}`);
  out("");
}

/** Stage: capture a project idea (only when nothing at all exists yet). */
export async function resumeIdeaStep(opts: ResumeOptions): Promise<boolean> {
  const ideaPath = path.join(state.repoDir, "docs", "IDEA.md");
  if (fs.existsSync(ideaPath) || hasPrd()) return true;
  if (opts.nonInteractive) {
    out("  No idea or PRD captured yet. Next: run the launcher to capture an idea:");
    command("forge-launcher");
    return false;
  }
  out("  No project idea or PRD captured yet in this repository.");
  out("");
  const choice = await promptSelect("What would you like to do?", [
    { value: "capture", label: "Capture your project idea now", hint: "writes docs/IDEA.md" },
    { value: "cli", label: "Open the harness CLI to run /forge-auto-build-prd manually" },
    { value: "stop", label: "Stop here" },
  ], { initial: "capture" });
  if (choice === "stop") return false;
  if (choice === "cli") {
    await openCliFor("/forge-auto-build-prd Use docs/IDEA.md as the project idea");
    return false;
  }
  if (opts.dryRun) {
    warn("Dry-run: would prompt for an idea and write docs/IDEA.md.");
    return false;
  }
  const ideaText = await promptMultiline("Describe your project idea");
  if (!ideaText.trim()) {
    warn("No idea text entered; stopping here.");
    return false;
  }
  fs.mkdirSync(path.join(state.repoDir, "docs"), { recursive: true });
  const content = [
    "# Project Idea",
    "",
    ideaText,
    "",
    "---",
    "",
    `> Generated by forge-launcher (resume) on ${new Date().toISOString().replace(/\.\d{3}Z$/, "Z")}`,
    "> Use this file as input for: `@workspace /forge-auto-build-prd Use docs/IDEA.md as the project idea`",
    "",
  ].join("\n");
  fs.writeFileSync(ideaPath, content);
  fs.copyFileSync(ideaPath, path.join(state.repoDir, "IDEA.md"));
  ok(`Idea saved to: ${link(ideaPath)}`);
  return true;
}

/** Stage: turn the idea into a reviewed PRD. */
export async function resumePrdStep(opts: ResumeOptions): Promise<boolean> {
  if (hasPrd()) return true;
  if (!fs.existsSync(path.join(state.repoDir, "docs", "IDEA.md"))) return true;
  if (opts.nonInteractive) {
    out("  No PRD yet. Next: draft the PRD from docs/IDEA.md:");
    command(headlessCmdFor(`/forge-auto-build-prd ${PRD_HEADLESS_MSG}`));
    return false;
  }
  out("  No PRD yet. docs/IDEA.md is ready to become a reviewed PRD.");
  out("");
  const choice = await promptSelect("How do you want to create the PRD?", [
    { value: "draft", label: "Auto-draft it now", hint: "headless forge-auto-build-prd" },
    { value: "cli", label: "Open the harness CLI to draft it manually" },
    { value: "stop", label: "Stop here" },
  ], { initial: "draft" });
  if (choice === "stop") return false;
  if (choice === "cli") {
    await openCliFor("/forge-auto-build-prd Use docs/IDEA.md as the project idea");
    return false;
  }
  const ran = await runSkillHeadless(`/forge-auto-build-prd ${PRD_HEADLESS_MSG}`, opts);
  if (!ran) return false;
  await draftCommit("docs: add auto-drafted PRD");
  if (hasPrd()) {
    state.prdAdded = true;
    ok("PRD generated.");
    out("");
    out("  Review it before continuing:");
    out(`    - ${link(path.join(state.repoDir, "docs", "PRD.md"))}`);
    if (fs.existsSync(path.join(state.repoDir, "docs", "product-vision.md"))) {
      out("    - " + link(path.join(state.repoDir, "docs", "product-vision.md")) + " (decomposed) + docs/features/*.md");
    } else {
      out("    - docs/PRD.md is monolithic (no decomposition)");
    }
  } else {
    await diagnoseAutoDraftFail("forge-auto-build-prd");
    return false;
  }
  return true;
}

/** Stage: generate the agent team from the PRD. */
export async function resumeTeamStep(opts: ResumeOptions): Promise<boolean> {
  if (hasGeneratedTeam()) return true;
  if (!hasPrd()) return true;
  if (opts.nonInteractive) {
    out("  No agent team yet. Next: generate the team from the PRD:");
    command(headlessCmdFor(`${buildTeamPrompt(prdSourceForTeam(), state.harness)} Auto-proceed with default assumptions and no questions.`));
    return false;
  }
  out("  No agent team yet. docs/PRD.md is ready for team generation.");
  out("");
  const choice = await promptSelect("How do you want to generate the team?", [
    { value: "draft", label: "Auto-draft it now", hint: "headless forge-build-agent-team" },
    { value: "cli", label: "Open the harness CLI to build the team manually" },
    { value: "stop", label: "Stop here" },
  ], { initial: "draft" });
  if (choice === "stop") return false;
  if (choice === "cli") {
    await openCliFor(buildTeamPrompt("docs/PRD.md", state.harness));
    return false;
  }
  const prdSource = prdSourceForTeam();
  const ran = await runSkillHeadless(
    `${buildTeamPrompt(prdSource, state.harness)} Auto-proceed with default assumptions and no questions.`,
    opts,
  );
  if (!ran) return false;
  await draftCommit("feat: generate auto-drafted agent team");
  if (hasGeneratedTeam()) {
    ok("Agent team generated.");
    out("");
    out("  Review the generated team before building:");
    out(`    - Agents : ${link(harnessAgentsDir() + "/")}`);
    out(`    - Skills : ${link(harnessSkillsDir() + "/")}`);
  } else {
    await diagnoseAutoDraftFail("forge-build-agent-team");
    return false;
  }
  return true;
}


/** Stage: start/resume the build via the engine or hand off to the harness. */
export async function resumeEngineStep(opts: ResumeOptions): Promise<void> {
  const engine = readEngineState();

  if (engine) {
    printEngineStatus(engine);
    if (opts.nonInteractive) {
      if (engine.status === "complete") {
        out("  The engine run is complete. Next:");
        command(`tail -f ${path.join(state.repoDir, "docs", "PROGRESS.md")}`);
      } else if (engine.status === "running") {
        warn("The engine is already running in the background - do not start a second run.");
        printMonitorCommands();
      } else {
        out("  Next: resume the engine run from WORKFLOW-STATE.json:");
        command(`npx forge-launcher ${engineRunArgs().join(" ")}`);
      }
      return;
    }
    if (engine.status === "complete") {
      ok("The build is complete.");
      const open = await promptYesNo("Open the harness CLI to continue (add features, review, etc.)?", "n");
      if (open === "y") await openCliFor("/forge-orchestrate-build");
      return;
    }
    if (engine.status === "running") {
      warn("The engine is currently running in the background.");
      const stopChoice = await promptSelect("The engine is running. What would you like to do?", [
        { value: "monitor", label: "Monitor the build (print commands)", hint: "default" },
        { value: "stop", label: "Stop the engine after the current task" },
        { value: "back", label: "Go back" },
      ], { initial: "monitor" });
      if (stopChoice === "stop") {
        await stopEngine(opts);
      } else if (stopChoice === "monitor") {
        printMonitorCommands();
      }
      return;
    }
    const choice = await promptSelect("What would you like to do?", [
      { value: "resume", label: "Resume the engine run", hint: "continues from WORKFLOW-STATE.json" },
      { value: "cli", label: "Open the harness CLI for project-orchestrator" },
      { value: "logs", label: "Print monitor / log commands" },
      { value: "stop", label: "Stop here" },
    ], { initial: "resume" });
    switch (choice) {
      case "resume": await runEngineDetached(opts); break;
      case "cli": await openCliFor(autobuildCommand()); break;
      case "logs": printMonitorCommands(); break;
    }
    return;
  }

  // No engine run yet (the team-absent case is handled by the earlier stages).
  if (opts.nonInteractive) {
    out("  Next: compile the manifest and start the engine:");
    command(`npx forge-launcher ${engineRunArgs().join(" ")}`);
    return;
  }
  await engineDecision(opts);
  if (state.engineStarted) return;
  const open = await promptYesNo(`Open the ${state.harnessLabel} CLI to build manually now?`, "n");
  if (open === "y") await openCliFor(autobuildCommand());
}

export function resumeSummary(): void {
  out("");
  out("════════════════════════════════════════════════════════");
  out("  forge-launcher resume: where to pick up");
  out("════════════════════════════════════════════════════════");
  out("");
  out(`  Repository  : ${link(state.repoDir)}`);
  out(`  Harness     : ${state.harnessLabel}`);
  const ideaPath = path.join(state.repoDir, "docs", "IDEA.md");
  out(`  Idea file   : ${fs.existsSync(ideaPath) ? link(ideaPath) : "none"}`);
  out(`  PRD         : ${hasPrd() ? link(path.join(state.repoDir, "docs", "PRD.md")) : "none"}`);
  out(`  Agent team  : ${hasGeneratedTeam() ? link(harnessAgentsDir() + "/") : "none"}`);
  out("");
  out("  Next steps:");
  out("");
  if (state.engineStarted) {
    out(`  1. The workflow engine is building in the background.`);
    out(`     Monitor: tail -f ${path.join(state.repoDir, "docs", "PROGRESS.md")}`);
  } else if (!hasPrd()) {
    out(`  1. Run forge-launcher to continue: forge-launcher`);
  } else if (!hasGeneratedTeam()) {
    out(`  1. Generate the agent team: open the harness and run /forge-build-agent-team`);
  } else {
    out(`  1. Build: npx forge-launcher ${engineRunArgs().join(" ")}`);
    out(`  2. Or in the harness: ${autobuildCommand()}`);
  }
  out("");
}

/**
 * Re-enters an existing forge project at its current stage (idea → PRD → team →
 * build) so a run paused for review can be picked up later. Full interactive
 * wizard in a TTY; prints state + exact next commands with --non-interactive.
 */
export async function runResume(opts: ResumeOptions = {}): Promise<number> {
  prompts.nonInteractive = Boolean(opts.nonInteractive);
  const repoDir = opts.repo ? path.resolve(opts.repo) : detectRepoRoot();
  if (!fs.existsSync(path.join(repoDir, ".git"))) {
    fail(`Not a git repository: ${repoDir}`);
    out("");
    info("Run forge-launcher to create and bootstrap a new project first.");
    return 1;
  }
  setupStateForRepo(repoDir);

  printResumeWhere();

  let go = await resumeIdeaStep(opts);
  if (!go) { resumeSummary(); return 0; }
  go = await resumePrdStep(opts);
  if (!go) { resumeSummary(); return 0; }
  go = await resumeTeamStep(opts);
  if (!go) { resumeSummary(); return 0; }
  await resumeEngineStep(opts);
  resumeSummary();
  return 0;
}
